### ISSUE TITLE
Comparison with thesis

### ISSUE THREAD

**Issue by rigille** [CertiKOS/rbgs#5]
I'm curious, how does this library compare with the thesis [here](https://certikos.github.io/rbgs-papers/thesis/thesis.pdf)? Do all concepts have some corresponding code or is it more of a work in progress?

**Comment by jeremie-koenig** [comment]
Hi Rígille, thank you for your interest!

The interaction specification monad of Chapter 6 is implemented in `models/IntSpec.v` and CompCertO (Part III) is implemented in the `compcerto` branch of our CertiKOS/compcert repository, which is also used as the `compcert/` submodule here. Generally speaking it should be quite close to what is described in the thesis, although we might have made tweaks here and there, and some aspects are still a work in progress.

Sorry for the late response and feel free to follow up if you have any remaining question.

**Comment by rigille** [comment]
I almost forgot to answer, but thanks! I'm trying to understand everything and write some more examples.
